# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_template.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets
from PySide2.QtWidgets import QWidget, QDialog
from main_action import Views_Main_Window
from widgets.tabwidget import CustomTabWidget


class Ui_MainWindow(Views_Main_Window):
    def setupUi(self, MainWindow):

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1266, 874)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = CustomTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 20, 1271, 1261))
        self.tabWidget.setProperty("5", "")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")

        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(0, 10, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK JP")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLineWidth(4)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(140, 10, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK JP")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setLineWidth(4)
        self.label_4.setObjectName("label_4")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab)
        self.pushButton_8.setGeometry(QtCore.QRect(440, 40, 31, 21))
        self.pushButton_8.setObjectName("pushButton_8")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(140, 40, 111, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_4.setGeometry(QtCore.QRect(190, 40, 101, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(470, 40, 111, 21))
        self.comboBox.setObjectName("comboBox")

        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_6.setGeometry(QtCore.QRect(970, 120, 141, 16))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(1120, 120, 131, 20))
        self.label_9.setObjectName("label_9")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_5.setGeometry(QtCore.QRect(970, 90, 141, 16))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_3.setGeometry(QtCore.QRect(970, 60, 141, 16))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(950, 20, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK JP")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setLineWidth(4)
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(1120, 90, 131, 20))
        self.label_8.setObjectName("label_8")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(1040, 560, 53, 16))
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab)
        self.pushButton_5.setGeometry(QtCore.QRect(1130, 480, 101, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_4.setGeometry(QtCore.QRect(970, 600, 91, 41))
        self.pushButton_4.setObjectName("pushButton_4")

        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(970, 520, 81, 21))
        self.label_2.setMaximumSize(QtCore.QSize(81, 16777215))
        self.label_2.setObjectName("label_2")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab)
        self.pushButton_7.setGeometry(QtCore.QRect(1130, 560, 101, 41))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(1030, 520, 53, 16))
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_6.setGeometry(QtCore.QRect(1130, 520, 101, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(970, 560, 81, 21))
        self.label_5.setObjectName("label_5")
        # self.treeWidget.raise_()
        self.label.raise_()
        self.label_4.raise_()
        self.pushButton_8.raise_()
        self.lineEdit.raise_()
        # self.lineEdit_2.raise_()
        self.lineEdit_4.raise_()
        self.comboBox.raise_()
        # self.label_7.raise_()
        self.pushButton_4.raise_()

        self.lineEdit_6.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.lineEdit_3.raise_()
        self.pushButton_5.raise_()
        self.label_11.raise_()
        # self.tableWidget.raise_()
        self.lineEdit_5.raise_()
        self.label_2.raise_()
        self.label_10.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(10, 10, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK JP")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setLineWidth(4)
        self.label_16.setObjectName("label_16")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.tab_2)
        self.dateTimeEdit.setGeometry(QtCore.QRect(10, 40, 194, 25))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.tab_2)
        self.dateTimeEdit_2.setGeometry(QtCore.QRect(10, 80, 194, 25))
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_10.setGeometry(QtCore.QRect(210, 40, 131, 61))
        self.pushButton_10.setObjectName("pushButton_10")
        self.tableWidget_6 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_6.setGeometry(QtCore.QRect(10, 110, 1011, 731))
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(10)
        self.tableWidget_6.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(6, item)
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(192, 252, 187))
        self.tableWidget_6.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        # item.setFlags(
        #     QtCore.Qt.ItemIsSelectable
        #     | QtCore.Qt.ItemIsUserCheckable
        #     | QtCore.Qt.ItemIsTristate
        # )
        self.tableWidget_6.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        # item.setFlags(
        #     QtCore.Qt.ItemIsSelectable
        #     | QtCore.Qt.ItemIsDragEnabled
        #     | QtCore.Qt.ItemIsDropEnabled
        #     | QtCore.Qt.ItemIsUserCheckable
        #     | QtCore.Qt.ItemIsEnabled
        # )
        self.tableWidget_6.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget_6.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setItem(1, 0, item)
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(370, 60, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK JP")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setLineWidth(4)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(350, 10, 151, 41))
        self.label_18.setObjectName("label_18")
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(510, 10, 151, 41))
        self.label_20.setObjectName("label_20")
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(510, 60, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK JP")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setLineWidth(4)
        self.label_19.setObjectName("label_19")
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(1040, -10, 151, 41))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        self.label_22.setGeometry(QtCore.QRect(1110, 0, 71, 41))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        self.label_23.setGeometry(QtCore.QRect(1110, 40, 71, 41))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.tab_2)
        self.label_24.setGeometry(QtCore.QRect(1110, 80, 71, 41))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.tab_2)
        self.label_25.setGeometry(QtCore.QRect(1190, 0, 71, 41))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.tab_2)
        self.label_26.setGeometry(QtCore.QRect(1190, 40, 71, 41))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.tab_2)
        self.label_27.setGeometry(QtCore.QRect(1190, 80, 71, 41))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.tab_2)
        self.label_28.setGeometry(QtCore.QRect(1040, 120, 151, 41))
        self.label_28.setObjectName("label_28")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_11.setGeometry(QtCore.QRect(1030, 170, 101, 31))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_12.setGeometry(QtCore.QRect(1030, 200, 101, 31))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_13.setGeometry(QtCore.QRect(1030, 230, 101, 31))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_14.setGeometry(QtCore.QRect(1140, 200, 101, 31))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_15.setGeometry(QtCore.QRect(1140, 230, 101, 31))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_16.setGeometry(QtCore.QRect(1140, 170, 101, 31))
        self.pushButton_16.setObjectName("pushButton_16")
        self.textEdit = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit.setGeometry(QtCore.QRect(1030, 310, 131, 31))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_2.setGeometry(QtCore.QRect(1030, 370, 201, 61))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_29 = QtWidgets.QLabel(self.tab_2)
        self.label_29.setGeometry(QtCore.QRect(1030, 260, 151, 41))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.tab_2)
        self.label_30.setGeometry(QtCore.QRect(1030, 330, 151, 41))
        self.label_30.setObjectName("label_30")
        self.pushButton_17 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_17.setGeometry(QtCore.QRect(1030, 450, 101, 51))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_18.setGeometry(QtCore.QRect(1140, 450, 101, 51))
        self.pushButton_18.setObjectName("pushButton_18")
        self.label_31 = QtWidgets.QLabel(self.tab_2)
        self.label_31.setGeometry(QtCore.QRect(670, 10, 151, 41))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.tab_2)
        self.label_32.setGeometry(QtCore.QRect(670, 60, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK JP")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setLineWidth(4)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.tab_2)
        self.label_33.setGeometry(QtCore.QRect(810, 10, 151, 41))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.tab_2)
        self.label_34.setGeometry(QtCore.QRect(810, 60, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK JP")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setLineWidth(4)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.tab_2)
        self.label_35.setGeometry(QtCore.QRect(880, 10, 151, 41))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.tab_2)
        self.label_36.setGeometry(QtCore.QRect(880, 60, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK JP")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setLineWidth(4)
        self.label_36.setObjectName("label_36")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_3.setGeometry(QtCore.QRect(0, 20, 301, 191))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(2)
        self.tableWidget_3.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        # item.setFlags(QtCore.Qt.ItemIsEditable)
        self.tableWidget_3.setItem(0, 1, item)
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_9.setGeometry(QtCore.QRect(210, 40, 91, 31))
        self.pushButton_9.setObjectName("pushButton_9")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_4.setGeometry(QtCore.QRect(320, 20, 221, 181))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(2)
        self.tableWidget_4.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(4, 0, item)
        self.pushButton = QtWidgets.QPushButton(self.tab_3)
        self.pushButton.setGeometry(QtCore.QRect(370, 210, 121, 31))
        self.pushButton.setObjectName("pushButton")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(0, 0, 101, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(320, 0, 101, 16))
        self.label_13.setObjectName("label_13")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_5.setGeometry(QtCore.QRect(560, 50, 211, 181))
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(2)
        self.tableWidget_5.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(4, 0, item)
        self.checkBox = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox.setGeometry(QtCore.QRect(670, 130, 80, 22))
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_2.setGeometry(QtCore.QRect(670, 160, 80, 22))
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_3.setGeometry(QtCore.QRect(670, 190, 80, 22))
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_4.setGeometry(QtCore.QRect(670, 100, 80, 22))
        self.checkBox_4.setText("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_5.setGeometry(QtCore.QRect(670, 70, 80, 22))
        self.checkBox_5.setText("")
        self.checkBox_5.setObjectName("checkBox_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_2.setGeometry(QtCore.QRect(560, 20, 101, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_3.setGeometry(QtCore.QRect(660, 20, 111, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(560, -10, 181, 31))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setGeometry(QtCore.QRect(790, -10, 181, 31))
        self.label_15.setObjectName("label_15")
        self.listView = QtWidgets.QListView(self.tab_3)
        self.listView.setGeometry(QtCore.QRect(790, 20, 251, 211))
        self.listView.setObjectName("listView")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_7.setGeometry(QtCore.QRect(100, 40, 111, 31))
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_8.setGeometry(QtCore.QRect(420, 40, 111, 31))
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_9.setGeometry(QtCore.QRect(420, 70, 111, 31))
        self.lineEdit_9.setText("")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_10.setGeometry(QtCore.QRect(420, 100, 111, 31))
        self.lineEdit_10.setText("")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_11.setGeometry(QtCore.QRect(420, 130, 111, 31))
        self.lineEdit_11.setText("")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_12.setGeometry(QtCore.QRect(420, 160, 111, 31))
        self.lineEdit_12.setText("")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.tabWidget.addTab(self.tab_3, "")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(320, 0, 71, 31))
        self.label_3.setObjectName("label_3")

        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1266, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.add_goods_action = QtWidgets.QAction(MainWindow)
        self.add_goods_action.setObjectName("add_goods_action")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_CSV = QtWidgets.QAction(MainWindow)
        self.action_CSV.setObjectName("action_CSV")
        self.menuFile.addSeparator()
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action)
        self.menu.addAction(self.add_goods_action)
        self.menu.addAction(self.action_4)
        self.menu.addAction(self.action_CSV)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        # self.label_7.setBuddy(self.label_2)
        # self.label_2.setBuddy(self.label_2)
        # self.label_5.setBuddy(self.label_2)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton_9.clicked.connect(self.label_3.update)
        self.lineEdit_7.editingFinished.connect(self.label_3.repaint)
        # self.tableWidget.cellClicked['int','int'].connect(self.tableWidget.sortByColumn)
        # self.tableWidget.cellActivated['int','int'].connect(self.tableWidget.sortByColumn)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_8.setText(_translate("MainWindow", "x"))
        self.pushButton_5.setText(_translate("MainWindow", "готово"))
        self.pushButton_4.setText(_translate("MainWindow", "очистить"))
        self.label_2.setText(_translate("MainWindow", "сумма"))
        self.pushButton_7.setText(_translate("MainWindow", "терминал"))
        self.pushButton_6.setText(_translate("MainWindow", "карта"))
        self.label_5.setText(_translate("MainWindow", "прибыль"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Товары")
        )
        self.label_16.setText(_translate("MainWindow", "Статистика"))
        self.pushButton_10.setText(_translate("MainWindow", "Показать"))
        item = self.tableWidget_6.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_6.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_6.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_6.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_6.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_6.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget_6.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget_6.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Арт"))
        item = self.tableWidget_6.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Название"))
        item = self.tableWidget_6.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Дата"))
        item = self.tableWidget_6.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Цена"))
        item = self.tableWidget_6.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Наценка"))
        item = self.tableWidget_6.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "К-ть"))
        item = self.tableWidget_6.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Сумма"))
        item = self.tableWidget_6.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Прибуток"))
        item = self.tableWidget_6.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Оплата"))
        __sortingEnabled = self.tableWidget_6.isSortingEnabled()
        self.tableWidget_6.setSortingEnabled(False)
        item = self.tableWidget_6.item(0, 1)
        item.setText(_translate("MainWindow", "3105"))
        item = self.tableWidget_6.item(0, 2)
        item.setText(
            _translate("MainWindow", "Масло RockShow 5WT 10ml, 11 4015.354.010")
        )
        item = self.tableWidget_6.item(0, 3)
        item.setText(_translate("MainWindow", "0.2"))
        item = self.tableWidget_6.item(0, 4)
        item.setText(_translate("MainWindow", "0%"))
        item = self.tableWidget_6.item(0, 5)
        item.setText(_translate("MainWindow", "0.2"))
        item = self.tableWidget_6.item(0, 6)
        item.setText(_translate("MainWindow", "322"))
        item = self.tableWidget_6.item(0, 7)
        item.setText(_translate("MainWindow", "6"))
        self.tableWidget_6.setSortingEnabled(__sortingEnabled)
        self.label_17.setText(_translate("MainWindow", "40"))
        self.label_18.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p><span style=" font-size:20pt; vertical-align:sub;">получено средств</span></p></body></html>',
            )
        )
        self.label_20.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p><span style=" font-size:20pt; vertical-align:sub;">прибыль с продаж</span></p></body></html>',
            )
        )
        self.label_19.setText(_translate("MainWindow", "40"))
        self.label_21.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p><span style=" font-size:20pt; vertical-align:sub;">Касса</span></p><p><br/></p></body></html>',
            )
        )
        self.label_22.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p><span style=" font-size:20pt; vertical-align:sub;">Готовка</span></p><p><br/></p></body></html>',
            )
        )
        self.label_23.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p><span style=" font-size:20pt; vertical-align:sub;">Карта</span></p><p><br/></p></body></html>',
            )
        )
        self.label_24.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p><span style=" font-size:20pt; vertical-align:sub;">Счет</span></p><p><br/></p></body></html>',
            )
        )
        self.label_25.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p><span style=" font-size:20pt; vertical-align:sub;">0</span></p><p><br/></p></body></html>',
            )
        )
        self.label_26.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p><span style=" font-size:20pt; vertical-align:sub;">0</span></p><p><br/></p></body></html>',
            )
        )
        self.label_27.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p><span style=" font-size:20pt; vertical-align:sub;">0</span></p><p><br/></p></body></html>',
            )
        )
        self.label_28.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p><span style=" font-size:20pt; vertical-align:sub;">Операции</span></p><p><br/></p></body></html>',
            )
        )
        self.pushButton_11.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_12.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_13.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_14.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_15.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_16.setText(_translate("MainWindow", "PushButton"))
        self.label_29.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p><span style=" font-size:20pt; vertical-align:sub;">Сумма</span></p></body></html>',
            )
        )
        self.label_30.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p><span style=" font-size:20pt; vertical-align:sub;">Комментарий</span></p></body></html>',
            )
        )
        self.pushButton_17.setText(_translate("MainWindow", "Положить "))
        self.pushButton_18.setText(_translate("MainWindow", "Взять"))
        self.label_31.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p><span style=" font-size:20pt; vertical-align:sub;">общая прибыль</span></p></body></html>',
            )
        )
        self.label_32.setText(_translate("MainWindow", "40"))
        self.label_33.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p><span style=" font-size:20pt; vertical-align:sub;">аванс</span></p></body></html>',
            )
        )
        self.label_34.setText(_translate("MainWindow", "40"))
        self.label_35.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p><span style=" font-size:20pt; vertical-align:sub;">затраты</span></p></body></html>',
            )
        )
        self.label_36.setText(_translate("MainWindow", "40"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_2),
            _translate("MainWindow", "Касса/статистика"),
        )
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "параметр"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "значения"))
        __sortingEnabled = self.tableWidget_3.isSortingEnabled()
        self.tableWidget_3.setSortingEnabled(False)
        item = self.tableWidget_3.item(0, 0)
        item.setText(_translate("MainWindow", "курс"))
        self.tableWidget_3.setSortingEnabled(__sortingEnabled)
        self.pushButton_9.setText(_translate("MainWindow", "установить "))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "параметр"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "значения"))
        __sortingEnabled = self.tableWidget_4.isSortingEnabled()
        self.tableWidget_4.setSortingEnabled(False)
        item = self.tableWidget_4.item(0, 0)
        item.setText(_translate("MainWindow", "сервер"))
        item = self.tableWidget_4.item(1, 0)
        item.setText(_translate("MainWindow", "порт"))
        item = self.tableWidget_4.item(2, 0)
        item.setText(_translate("MainWindow", "адрес отправит"))
        item = self.tableWidget_4.item(3, 0)
        item.setText(_translate("MainWindow", "пароль"))
        item = self.tableWidget_4.item(4, 0)
        item.setText(_translate("MainWindow", "адрес получателя"))
        self.tableWidget_4.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("MainWindow", "Отправить отчет"))
        self.label_12.setText(_translate("MainWindow", "курс USD/ГРН"))
        self.label_13.setText(_translate("MainWindow", "настройки email"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "категория"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "v"))
        __sortingEnabled = self.tableWidget_5.isSortingEnabled()
        self.tableWidget_5.setSortingEnabled(False)
        item = self.tableWidget_5.item(0, 0)
        item.setText(_translate("MainWindow", "Велосипеди"))
        item = self.tableWidget_5.item(1, 0)
        item.setText(_translate("MainWindow", "Компоненти"))
        item = self.tableWidget_5.item(2, 0)
        item.setText(_translate("MainWindow", "Одяг"))
        item = self.tableWidget_5.item(3, 0)
        item.setText(_translate("MainWindow", "Аксесуари"))
        item = self.tableWidget_5.item(4, 0)
        item.setText(_translate("MainWindow", "Майстерня"))
        self.tableWidget_5.setSortingEnabled(__sortingEnabled)
        self.pushButton_2.setText(_translate("MainWindow", "экспорт CSV"))
        self.pushButton_3.setText(_translate("MainWindow", "импорт CSV"))
        self.label_14.setText(_translate("MainWindow", "Экспорт/Импорт базы данных"))
        self.label_15.setText(_translate("MainWindow", "Принтер"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Наличие")
        )
        self.label_3.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p><span style=" font-size:20pt; vertical-align:sub;">USD - </span></p></body></html>',
            )
        )
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menu.setTitle(_translate("MainWindow", "Товары"))
        self.menu_2.setTitle(_translate("MainWindow", "Касса"))
        self.menu_3.setTitle(_translate("MainWindow", "Наличие"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.action.setText(_translate("MainWindow", "выход"))
        self.add_goods_action.setText(_translate("MainWindow", "добавить товары"))
        self.action_4.setText(_translate("MainWindow", "добавить категории"))
        self.action_CSV.setText(_translate("MainWindow", "добавить товары из CSV"))
        self.statusBar = QtWidgets.QStatusBar(self.tab)
        MainWindow.setStatusBar(self.statusBar)
        self.add_actions()
